# Run continuous integration

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
      - name: Set up Java
        uses: actions/setup-java@215b7e5f829ab9cac114c149667e57dc1b70b4bc # v2.5.2
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: false
          cache: 'maven'
      - name: Build with Maven
        run: 'mvn package'
        shell: bash
